### ISSUE TITLE
Facing interruptions with personal ChatGPT responses: Stops mid-sentence without errors. Any insight

### ISSUE THREAD

**Issue by MYSeaIT** [aduryagin/gpt#1]
However, I've come across a significant issue wherein the chatbot abruptly stops in the middle of a conversation without displaying any errors or warnings. It appears that the main problem is related to how the chat response is being streamed, causing only the initial part of the response to be received. Removing 'stream:true' from #src/App.tsx:137 should theoretically resolve this by allowing the fetch function to return the entire response. However, doing so results in the chatbot's response stopping altogether.

**Comment by aduryagin** [comment]
Hi, Adam. Thanks for the feedback. Seems like OpenAI updated something in their API. Unfortunately, I do not see any reason to maintain this project because you can have voice conversations in the mobile app and obviously there are much better maintained solutions for storing your prompts.
